name: 'Backend CI'
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  lint-job:
    name: 'Linting Job'
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          
      - name: Install dependencies
        run: |
          cd ./starter/backend
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --dev

      - name: Run lint check
        run: cd ./starter/backend && pipenv run lint
  test-job:
    name: 'Testing Job'
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          
      - name: Install dependencies
        run: |
          cd ./starter/backend
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install pytest --dev
          pipenv install --dev

      - name: Run tests
        run: |
          cd ./starter/backend 
          pipenv run test
  # build 
  build:
    needs: [lint-job, test-job]
    runs-on: ubuntu-latest 

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          cd ./starter/backend
          docker build -t backend .